### ISSUE TITLE
Feature : Autodiscover sniff ?

### ISSUE THREAD

**Issue by ncou** [gskema/phpcs-type-sniff#11]
Hi,

Nice piece of code ! 
Just to know if there is a plan for your project to be compatible with the "autodiscovery" function made with this composer plugin : https://github.com/Dealerdirect/phpcodesniffer-composer-installer

This could avoid to add manually your sniff. I find this feature really usefull when you have a bunch of phpcs library to add in your own coding standards.

In any case, keep up the good work.

**Comment by gskema** [comment]
Hi, I'll check it out but I'm 95% sure it won't work because I deliberately tried to avoid creating a phpcs package/standard. The setup/configuration is a real pain.

**Comment by ncou** [comment]
Hi, after reflexion i think it will not "really" work because you need to create one file rules.xml to be discovered and this mean you need to provide a "default" configuration without the case "property name=useReflection value=true", so this could lead some of the user to doesn't use this option. => I hope i am clear.

But i could try to do a few tests to see if the package could be made as a phpcs package with autodiscovery (with one default config) could be made.

**Comment by gskema** [comment]
Closing this issue because there are no plans no make it work with an auto installer. This sniff deliberately has custom, complex config and avoid phpcs xml mess
