### ISSUE TITLE
Change "warning" level to "error" level doesn't work

### ISSUE THREAD

**Issue by ncou** [gskema/phpcs-type-sniff#12]
Hi,

I want to change the "warning" level to an "error" level to stop the build if the sniff is not respected. I use the "classic" phpcs rules tag "<type>error</type>", but this value seems to be ignored. Is there a way to add this behavior ? Thanks.
`
<rule ref="Gskema.Sniffs.CompositeCodeElement.FqcnConstSniff">
            <type>error</type>
</rule>
`

**Comment by gskema** [comment]
Hi, it can be done but will require some changes :| Do you want to report all violations as errors or just specific one (e.g. FqcnConstSniff) ?

**Comment by ncou** [comment]
Hi,

In my case i want to report all the violations as errors. 
But perhaps you should allow the possibility to disable each rule (FqcnConstSniff.enabled/FqcnMethodSniff.enabled/FqcnPropSniff.enabled/FqcnDescriptionSniff.enabled) to keep some flexibility for other users of your sniff package.

**Comment by ncou** [comment]
Hi @gskema happy new year :) do you have all the informations needed ? Let me know if i can help.
Keep up the good work.

**Comment by gskema** [comment]
Hi, added new config options, described in https://github.com/gskema/phpcs-type-sniff/blob/master/README.md. Search for `reportType`. New version 0.15.0

**Comment by ncou** [comment]
Thank you very much !
