### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by brodkin** [gskema/phpcs-type-sniff#21]
The project appears to run flawlessly on PHP 8.2 as-is. I have tested it a project running PHP 8.2 as well as running the unit tests in PHP 8.2 with the current dependencies. Adding support should be as easy as updating composer.json to allow installation on a wider variety of PHP versions.

**Comment by gskema** [comment]
Might take a look but not sure when. 8.1 8.2 have some new feature which need to have at least basic support (not crash) here

**Comment by brodkin** [comment]
Thank you! I'd also be happy to support with a pull request if you're open to it. I've broken down the main language features that might have an impact below if you care to discuss.

**Probable Impact**
- Shorthand syntax for disjunctive normal types
- Universal use of null, false, and true as types

**No Expected Impact**
- Deprecated ${} string interpolation
- The ability to declare a class as readonly
- New Randomizer built-in class
- Constants defined in traits

**Comment by gskema** [comment]
Released 82.0.2 on 2023-01-17.

**Comment by mindaugasnakrosis** [comment]
@gskema imanoma kazkaip susisiekti su tavim butu? :) mindaugasnakr@gmail.com
