### ISSUE TITLE
Useless @InheritDoc comment

### ISSUE THREAD

**Issue by plumthedev** [gskema/phpcs-type-sniff#22]
Hello there, thanks for your great tool. I'm very like it, clever solution.
I was searching for tool like this and I finally managed to find something good.

I have a change request, maybe you will like it too or it can be helpful for others - I mean, I think that `@inheritDoc` parameter is no needed, when you are care of types, not documentation. I think that could be an option in configuration, if you want to force docs like this in your code or not. 

In my project I'm not using tools like PHPDocumentor to create a technical description of my API, it is internal project, but I still want to check and maintain types of my application. Your tool omits parts of code, which are fully typed and there is no doubts on them but for some reason, it want to force on me `@inheritDoc` always when I'm implementing a fully typed method, or even void without parameters.

Simple example:

```php
use Countable;

class Gskema implements Countable
{
    public function count(): int
    {
        // TODO: Implement count() method.
    }
}
```

It will generate error: `phpcs: Gskema.Sniffs.CompositeCodeElement.FqcnMethodSniff: Missing @inheritDoc tag. Remove duplicated parent PHPDoc content.`

I'm also using [slevomat/coding-standard](https://github.com/slevomat/coding-standard) and these guys has add a rule for [useless @InheritDoc comment](https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinguselessinheritdoccomment-)

Could you please reconsider my request and possibly add such a configuration condition - I would be very grateful :)

**Comment by gskema** [comment]
Hi which version are you using? When `useReflection` (default) is false this warning will not be activated. This is used to suppress warnings for methods which are extended and cannot change their types. We can add an option too, yes

**Comment by plumthedev** [comment]
Ok, cool - thank you so much.  
  
I'm using `"gskema/phpcs-type-sniff": "^81.0"` 

I want to use reflection because I don't want to have errors or warnings about missing native type hint declaration, I want to add doc blocks only there, where I cannot do it because of language construction.   
  
My target is to be fully typed on language level and support myself everywhere where I cannot use native type or I want to describe the structure. It is about better typed application. I don't think so that \`inheritDoc\` is needed for developers with my approach.

**Comment by gskema** [comment]
You can try `81.1.0` - it will be disabled by default
