### ISSUE TITLE
Add a Sniff for Object Like Arrays (Ie. Array Shapes)

### ISSUE THREAD

**Issue by dac514** [gskema/phpcs-type-sniff#3]
Hi! I'm coming here from r/php. To get here I clicked _"I wrote a PHPCS sniff to enforce type declaration **and documenting arrays**"_

It would be nice if this sniff encouraged Psalm type PhpDoc blocks for mixed arrays. Also known as array shapes. Maybe a warning with less severity than the others. Typed arrays being preferred. The syntax I am familiar with is Psalm:

> Psalm has support for object-like arrays, allowing you to specify types for all keys of an array if you so wish.

Examples of the syntax:

+ https://psalm.dev/r/1fb27903aa
+ https://psalm.dev/docs/annotating_code/type_syntax/array_types/#object-like-arrays

Maybe there are other syntax, but this is the one I am familiar with.

Thanks!

**Comment by gskema** [comment]
I personally haven't used this or other alternative notations (they don't seem to work in PhpStorm for me), I hope this will cover your cases:

https://github.com/gskema/phpcs-type-sniff/compare/array_shapes

This lib still assumes that array types are documented using `@param` (instead of `@psalm-param` or similar).

**Comment by dac514** [comment]
> (they don't seem to work in PhpStorm for me)

Me neither, the issue to watch (bump, cheerlead) is here:

+ https://youtrack.jetbrains.com/issue/WI-47052

**Comment by gskema** [comment]
@connerbw waiting for your input before merging and releasing

**Comment by dac514** [comment]
@gskema Ok I'll integrate it into one of my phpcs.xml configs  before the end of the week and get back to you.

**Comment by dac514** [comment]
Hi, I tested ie.

`composer require --dev gskema/phpcs-type-sniff:dev-array_shapes`

It works for me with the caveat is I can fool the sniff by changing:

```php
	/**
	 * @return array
	 */
```

```
XXX  | WARNING | Replace array type with typed array type in PHPDoc
     |         | for return value, .e.g.: "string[]" or
     |         | "SomeClass[]". Use mixed[] for generic arrays.
     |         | Correct array depth must be specified.
```

To:

```php
	/**
	 * @return array{
	 */
```

No warning.

**Comment by gskema** [comment]
Ok, but is that a bad thing? Why would someone write or leave a broken type (`array{` or `array{`)? Is `array{}` better/valid? There are infinite ways to write broken types. What do you suggest?

**Comment by dac514** [comment]
For me it's fine as is.

**Comment by gskema** [comment]
Thank you for the feedback, I think this is reasonable for the first iteration. I'm always up for improvements.
