### ISSUE TITLE
Symfony controller: Add type hint in PHPDoc tag for return value

### ISSUE THREAD

**Issue by ArthurHoaro** [gskema/phpcs-type-sniff#4]
Hi, thanks for the package, enforcing PHPDoc on arrays and removing useless PHPDoc is exactly what I need.

However there seems to be an issue with annotation PHPDoc:

```php
    /**
     * @Route("/things")
     */
    public function getThings(): Response
    {
        return new JsonResponse();
    }
```

generates

```
------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------
 24 | WARNING | Add type hint in PHPDoc tag for return value, e.g. "Response"
------------------------------------------------------------------------------
```

While
```php
    /**
     * @Route("/things")
     * @return Response
     */
    public function getThings(): Response
    {
        return new JsonResponse();
    }
```
generates

```
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 25 | WARNING | Useless PHPDoc
----------------------------------------------------------------------
```

The first report looks like a bug. The warning goes away if I remove the PHPDoc entirely, but I want to be able to use annotations.

I use a basic config as I'm just trying this:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/squizlabs/php_codesniffer/phpcs.xsd">

    <arg name="basepath" value="."/>
    <arg name="cache" value=".phpcs-cache"/>
    <arg name="colors"/>
    <arg name="extensions" value="php"/>

    <rule ref="PSR2"/>
    <rule ref="./vendor/gskema/phpcs-type-sniff/src/Sniffs/CompositeCodeElementSniff.php"/>

    <file>src/</file>
</ruleset>

```

**Comment by gskema** [comment]
The first report isn't a bug, there is an inspection for missing function parameters/return type. Ignoring this specific inspection could be controlled by a new config param.

Technically useful tags can be added using `FqcnMethodSniff.usefulTags`, however this one is immediately followed by parentheses with dynamic content. So tag parse regex will have to be adjusted. I'll try to come up with something soon. Thanks for the report!

**Comment by gskema** [comment]
Created a branch that solves tag parse + useless `@Route` tag issue:

https://github.com/gskema/phpcs-type-sniff/compare/dynamic_tags

The third problem (allowing missing param, return tags when type decl. are present) is a bit trickier, working on it. Is that common in your project? I personally use PhpStorm and it complains a lot about missing PHPDoc param, return tags.

**Comment by ArthurHoaro** [comment]
Thanks for the quick answer and fix.

> The third problem (allowing missing param, return tags when type decl. are present) is a bit trickier, working on it.

I didn't understand at first that it wasn't supported. Let me know if you find a solution, that would be a great feature.

> Is that common in your project?

Well yes, I try to only document not typed arrays. For example this raises a warning:

```php
    /**
     * @param string[] $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
```

Otherwise I use annotations mostly on Symfony controllers, such as `@Route`, `@ParamConverter`, or `@IsGranted`.

EDIT: I also use PHPStorm, but it uses PHPCS configuration so it really depends on that. :)

**Comment by gskema** [comment]
@ArthurHoaro I merged a new branch into master today. It has fixes for all 3 problems and an option for the third problem:
`<property name="FqcnMethodSniff.reportMissingTags" value="false"/>`
Any chance you could run it again on your project by using master version (composer `dev-master`) and give some feedback? Thank You

**Comment by ArthurHoaro** [comment]
It works perfectly, I'm sold!

Thanks again.

**Comment by gskema** [comment]
Cool! I will probably tag and release master early next week. I may still change the option name but it will all be in the README.
